% build_dgejsv_mex.m
openblas_lib = '/Users/cyae/OpenBLAS/lib';  % EDIT THIS PATH
gfortran_lib = '/opt/homebrew/Cellar/gcc/  % EDIT THIS PATH15.2.0_1/lib/gcc/15';

mex('-v','dgejsv_mex.c', ...
    ['-L' openblas_lib], '-lopenblas', ...
    ['-L' gfortran_lib], '-lgfortran', ...
    ['LDFLAGS=$LDFLAGS -Wl,-rpath,' openblas_lib ' -Wl,-rpath,' gfortran_lib]);
